### PR TITLE
update to charon v0.14.0

### PR DESCRIPTION
**Pull request by gsora**
This PR updates charon version to v0.14.0.

### CODE REVIEW

**Comment by eth2devops** [comment]
@gsora can you update the version in Chart.yaml files because the readme files are auto-generated from there. You will need to update the appVersion: "0.13.0" to appVersion: "0.14.0" and also the charon `version: 0.2.2` to `version: 0.2.3` and charon-cluster `version: 0.1.3` to `version: 0.1.4` so the helm release workflow publishes them correctly to the public artifactory. Thanks a lot for taking care of the release!

**Comment by gsora** [comment]
Will the helm chart workflow also regenerate the `values.yaml` file?

If yes, I'll just revert my last commit and edit the files you suggested.

**Comment by eth2devops** [comment]
> Will the helm chart workflow also regenerate the `values.yaml` file?
> 
> If yes, I'll just revert my last commit and edit the files you suggested.
@gsora 
It will not generate the values.yaml so you need to:
1- keep the values.yaml files updates
2- update the Chart.yaml files
3- run `make docs`

**Comment by eth2devops** [comment]
@gsora bumping this one up!

**Comment by gsora** [comment]
Done! 

Let's hold off merging this though, 0.14.1 should be around the corner.

**Comment by eth2devops** [comment]
> Done!
> 
> Let's hold off merging this though, 0.14.1 should be around the corner.

Thanks @gsora we will hold on this PR merge until 0.14.1

**Comment by eth2devops** [comment]
I will close this PR for the sake of the newer v0.14.3 PR

**Pull request closed without merging**
